### PR TITLE
Simulator: remove unused socket files

### PR DESCRIPTION
**Pull request by scgbckbone**
* remove non-used socket files after failure
* update gitignore with virtualenvs directories

### CODE REVIEW

**Comment by scgbckbone** [comment]
you mean the possibility to remove socket that is used with different client process ? -> not possible for two processes to share PID

but I was thinking about removing `instance` counter and instead use uuid4 (but maybe that is just me being overly paranoid)

**Comment by doc-hex** [comment]
right, I missed the PID... uuid seems overkill and makes for big ugly filenames.

**Comment by doc-hex** [comment]
- would prefer a for loop w/ else clause raising exc

**Comment by scgbckbone** [comment]
also lowered tries from 10 to 5 - imo enough, never seen getting more than one try refused.

**Comment by scgbckbone** [comment]
squashed

**Pull request merged**
