### PR TITLE
add hashes to requirements

### PR DESCRIPTION
**Pull request by scgbckbone**

### CODE REVIEW

**Comment by doc-hex** [comment]
- changing the >= into specific versions is not great.
- the specific versions you have on your system may not be a working combination on other systems.

**Comment by scgbckbone** [comment]
that is the tradeoff - you cannot have hashes without pinned versions

**Comment by doc-hex** [comment]
ok, make a new requirements file w/ the hashes, and a comment in the old (default) file pointing them to it

**Comment by scgbckbone** [comment]
not this time... using pip compile with version ranges in comments is bad idea. Mostly unpractical as it overwrites `requirements.txt` in place so devs have to add comments again after every update. Also pinning deterministic builds and providing way to upgrade them is what already available tools do. No need to reinvent square wheel again...

**Review by rllane17 — COMMENTED** [review]
>  @``

**Pull request closed without merging**
