### PR TITLE
Poetry

### PR DESCRIPTION
**Pull request by scgbckbone**
category:  nice to have (soft-fork) - legacy functionality untouched
```shell
$ poetry install --no-dev    --> instal dependencies
$ poetry install             --> install also dev dependencies
$ poetry install -E cli      --> install all dependencies (dev, cli)
```
and you can freely switch among them using poetry install
poetry will add/remove accordingly

using poetry is completely opt-in. It can be ignored at all and users
can continue using pip.

PROS: parallel download/install, ability to lock dependencies (poetry.lock), better requirements file generation (with hashes)
CONS: ?

### CODE REVIEW

**Comment by doc-hex** [comment]
sorry I don't see benefit over setup/pip

**Comment by scgbckbone** [comment]
I disagree here:
1. allows us to have deterministic dependencies for specific version- now with requirements defined as they are - we have no idea what users have installed, It is also not clear with which dependencies was the release candidate tested (yeah we do not have tests YET) and whether it works.
2. handles resolving and tracking transitive dependencies

**Comment by doc-hex** [comment]
`ckcc-protocol` is a library for others to use, so we cannot lock down specific versions of dependencies, but instead need to seek the largest range of working versions.

**Comment by scgbckbone** [comment]
I understand that - that is why requirements.txt is defined as is - yet we can provide (with each release) poetry.lock (or {version}_requirements.txt) with explicit dependencies with which we can say that this was tested and works. And then anyone can deterministically (with regards to python deps) install the same application.

This is not "I will die on this hill" kind of issue. One can use poetry even if it is not part of the project (added to .gitignore).

**"need to seek the largest range of working versions."** - I think there is no way we can say this - as it can be the case that with some combination of dependencies it does not work. 

**"is a library for others to use, so we cannot lock down specific versions of dependencies"** we can (and should) and it does not mean that they have to install them - they can still use pip/setup, but we would at least provide a deterministic deps set if anyone is interested to run the exact same (tested) code.

**Comment by nvk** [comment]
/moving this here, GitHub emails are broken to me./

NACK poetry.

KISS; Please don’t change/add dependency management. This could break many other projects.

**Comment by scgbckbone** [comment]
as I said - not gonna die on this hill. thanks for the review

**Pull request closed without merging**
